### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by 4F2E4A2E** [zippy1978/ghost4j#39]
Hello there!

Is there any particular reason why your project is not on maven central?
Coudl i walk you guys through that?

Just let me now if i can help, thanks!

**Comment by zippy1978** [comment]
Hi,

No there is no particular reason : I just never did it.

Your help will be appreciated of course :)

**Comment by 4F2E4A2E** [comment]
Sure thing no problem. When can i start? Can you add me as contributor?

**Comment by zippy1978** [comment]
Hi,

You are now a contributor.
You are ready to go !

**Comment by 4F2E4A2E** [comment]
Please go ahead and
1. create yourself an account with your username zippy1978  on https://issues.sonatype.org/secure/Signup!default.jspa
2. login into https://issues.sonatype.org/browse/OSSRH-16007 and add yourself as watcher of the ticket

By the way do you know gitter.im? A nice place to chat while hacking on github.

**Comment by 4F2E4A2E** [comment]
Please respond on Jira that you do own the domain and so on. 
Is that ok with you to change the package name?

We will have to change the groupid to: com.github.ghost4j

**Comment by zippy1978** [comment]
Thank you.
I will have a look at it when I have time.
But why do we I need to change the package name ?

**Comment by 4F2E4A2E** [comment]
We have to hange the groupid. The package name is only a suggestion, it's alright to leave it as is.

**Comment by 4F2E4A2E** [comment]
We are ready to release, though here some recommendations:
* let's raise the compile source version from 1.5 to 1.7. 
* move test resource files conform maven standard from / to /src/test/resources/
* raise the project version to 1.0.0 as semver.org recommends

**Comment by zippy1978** [comment]
Hi,

I am about to release.
However I will restore the original group id and I will not change the source level : there is no need to do it at the moment.

**Comment by zippy1978** [comment]
Release 1.0.0 is into staging repo

**Comment by 4F2E4A2E** [comment]
@groupid: as long as sonatype accepts it no reason to do otherwise and it's look like ithey did ;)
http://search.maven.org/#artifactdetails%7Corg.ghost4j%7Cghost4j%7C1.0.0%7Cjar

**Comment by zippy1978** [comment]
It's on the central :)
