### ISSUE TITLE
Ghost4J Release 1.0.1

### ISSUE THREAD

**Issue by 4F2E4A2E** [zippy1978/ghost4j#45]
Hello @zippy1978 !

We are planing to release tess4j soon and really could use the version 1.0.1 ( #40 and many more ) from ghost4j. Do you think we have any chance in releasing it this weekend?
I can go ahead and do all the integration testing and release it if you want, please let us now. 

cheers

**Comment by zippy1978** [comment]
Hi, sorry for the late reply. I'll try to release it during the week.

**Comment by zippy1978** [comment]
OK,
There is a problem, since the 1.0.1 pull request many tests are broken

  **Tests run: 48, Failures: 13, Errors: 14, Skipped: 0**

I cannot release that, I have to fix them first.

**Comment by zippy1978** [comment]
I had to downgrade JNA from 4.2.1 to 4.1.0 to prevent errors in native calls.
Release 1.0.1 is now available.

**Comment by umbreak** [comment]
It is also available already on Maven? Because ivy tells me it isn't and it is not defenitely on:

http://repo1.maven.org/maven2/org/ghost4j/ghost4j/1.0.1/ghost4j-1.0.1.pom

nor on: http://mvnrepository.com/artifact/org.ghost4j/ghost4j

**Comment by 4F2E4A2E** [comment]
Hi @zippy1978 , @umbreak is right, i can't find it on maven central. I just logged in on https://oss.sonatype.org and could not find the staging repository.

@umbreak ghost4j is beeing released only on maven repository, this is the right adress to lookup for it: http://search.maven.org/#search%7Cga%7C1%7Cghost4j

**Comment by 4F2E4A2E** [comment]
@zippy1978 I guess you did release it only on github. I will go ahead and prepare it to be released in maven central.

**Comment by zippy1978** [comment]
No, It is released on the Central already.

I just forgot to release the artifact.
This is done now and should be available soon.
