### ISSUE TITLE
Ghost4J supported GhostScript version

### ISSUE THREAD

**Issue by cccsssbbb** [zippy1978/ghost4j#47]
Hi zippy1978,

             I recently came across some PDF files, that can be parsed successfully using **GhostScript 9.18**, but not in **GhostScript 8.70**. By using this library, those PDFs cannot be parsed as well. Wondering would you have a **gs9.18 equivalent release** soon? Thank you.

cccsssbbb

**Comment by zippy1978** [comment]
Hi,

Ghost4J uses the Ghostscript native API.
So if GS 9.x is your default install, Ghost4J will use it.

Regards

**Comment by cccsssbbb** [comment]
if that is the case, do you have a function inside your api, to return the version of ghostscript in use?

**Comment by 4F2E4A2E** [comment]
Good question, it would be a nice feature to always print out the version of the currently loaded native api.

**Comment by zippy1978** [comment]
This feature already exists, you can get GS runtime info like this:

    public void testGetRevision() {

	GhostscriptRevision revision = Ghostscript.getRevision();

	assertNotNull(revision.getProduct());
	assertNotNull(revision.getCopyright());
	assertNotNull(revision.getRevisionDate());
	assertNotNull(revision.getNumber());

    }

Regards

**Comment by 4F2E4A2E** [comment]
What do you think about logging this information on every initialization?

**Comment by cccsssbbb** [comment]
It is a good practice to always print the gs version when in doubt
