### ISSUE TITLE
Release 1.0.1 not in Maven

### ISSUE THREAD

**Issue by umbreak** [zippy1978/ghost4j#48]
The documentation int he main Readme says that version 1.0.1 is available on Maven Central. However neither of those websites shows it:

http://repo1.maven.org/maven2/org/ghost4j/ghost4j/1.0.1/ghost4j-1.0.1.pom
http://mvnrepository.com/artifact/org.ghost4j/ghost4j

**Comment by 4F2E4A2E** [comment]
Issue duplicated, see #45 
Closing issue.
